# Generated by Django 3.1.3 on 2020-11-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_auto_20201116_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='classroom',
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='handler.teacher', verbose_name='Учитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default=1, max_length=120, verbose_name='Предмет'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
