# Generated by Django 3.1.3 on 2020-11-21 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handler', '0003_auto_20201121_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unique_code',
            field=models.CharField(default=1, max_length=11, verbose_name='Код студента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя на сайте'),
        ),
    ]
