# Generated by Django 3.1.3 on 2020-11-25 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0004_auto_20201121_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='comment',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='handler.teacher', verbose_name='Учитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_code',
            field=models.CharField(default='1', max_length=11, verbose_name='Код студента'),
        ),
    ]
