# Generated by Django 3.1.3 on 2020-11-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0005_auto_20201125_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группу', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученика', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учителя', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='negative',
        ),
        migrations.AddField(
            model_name='comment',
            name='results',
            field=models.TextField(default=1, verbose_name='Результаты'),
            preserve_default=False,
        ),
    ]
