# Generated by Django 3.1.3 on 2020-11-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0006_auto_20201126_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=120, verbose_name='Номер учителя'),
        ),
    ]
